### ISSUE TITLE
There may be a bug in srtg_resnet.py

### ISSUE THREAD

**Issue by RongchangLi** [alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates#1]
Hello, I find the line 177 in srtg_resnet.py is 
           ' nearest_n = embeddings2.scatter_(2,indices,1.)'.
This code will change parameter embeddings2.
So the next line:
           'b_consistent = embeddings2 - nearest_n'
will always get a zero result.
Is it a bug? Or did I neglect something?

**Comment by alexandrosstergiou** [comment]
Hi @Lilaoxie,
The operation was indded in-pace so `embeddings2` values would change and further making `nearest_n` only a reference to `embeddings2`. I’ve instead opted to have a recursive function for `soft_ncc`, because of an additional possible arithmetic underflow that was not accounted for.
Additionally, there is [a test script in `train/test_cyclic`](https://github.com/alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates/blob/998d0398137ad53e4ddf336d7d87891bdeaaf1d2/train/test_cyclic.py#L67-L76) to help understanding the functions functionality.

I am currently updating/polishing the code for this repo and improving its readability. So there may be some further updates based on feedback, in the coming weeks/month.

Best,
Alex

**Comment by alexandrosstergiou** [comment]
I will be closing this issue for the time being. Feel free to create a new one or re-open it for any future bugs.

Best,
Alex
